apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^process$', views.process, name="process"),
    url(r'^login$', views.login, name="login"),
    url(r'^login_attempt$', views.login_attempt, name="trylogin"),
    url(r'^logout$', views.logout, name="logout")
]

apps/secrets/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^most_popular$', views.most_popular, name="most_popular"),
    url(r'^create$', views.create, name="create"),
    url(r'^create_like/(?P<id>\d+)$',
        views.create_like, name="create_like")
]

dojo_secrets/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace="login")),
    url(r'^secrets/', include('apps.secrets.urls', namespace="secrets"))
]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt


class Verify(models.Manager):
    def regcheck(self, formdata):
        E_REG = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        P_REG = re.compile(r'^(?=.*[A-Z])(?=.*\d).+$')
        error = False
        errorlist = []
        for value in formdata:
            if len(formdata[value]) < 1:
                errorlist.append("Please fill out every field!")
                error = True
                return (error, errorlist)
        if not (formdata['first_name'].isalpha() and
                formdata['last_name'].isalpha()):
            error = True
            errorlist.append("Please only include letters in the name fields")
        if len(formdata['pword1']) < 8 or len(formdata['pword2']) < 8:
            error = True
            errorlist.append("Passwords must be at least 8 characters!")
        if not E_REG.match(formdata['email']):
            error = True
            errorlist.append("Please enter a valid email!")
        if formdata['pword1'] != formdata['pword2']:
            error = True
            errorlist.append("Oops! Passwords do not match")
        if not (P_REG.match(formdata['pword1']) or
                P_REG.match(formdata['pword2'])):
            error = True
            errorlist.append("Please include at least one uppercase and one\
            number in your password")
        return (error, errorlist)

    def logcheck(self, hashpwd, nohashpwd):
        if bcrypt.hashpw(nohashpwd.encode(), hashpwd.encode()) == hashpwd:
            return True
        else:
            return False


class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = Verify()

apps/secrets/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import User
from django.db.models import Count


class SecretManager(models.Manager):
    def secretlist(self, userid):
        secrets = self.order_by('-created_at')[:20]
        secretlist = []
        for secret in secrets:
            templist = []
            likes = Like.objects.filter(secret=secret)
            likebool = False
            for like in likes:
                if like.users.id == userid:
                    likebool = True
                    break
            templist.append(secret)
            templist.append(likebool)
            secretlist.append(templist)
        return secretlist

    def most_popular(self, userid):
        secrets = self.annotate(num_likes=Count('secretlikes')).order_by('-secretlikes')[:5]
        secretlist = []
        for secret in secrets:
            templist = []
            likes = Like.objects.filter(secret=secret)
            likebool = False
            for like in likes:
                if like.users.id == userid:
                    likebool = True
                    break
            templist.append(secret)
            templist.append(likebool)
            secretlist.append(templist)
        return secretlist


class Secret(models.Model):
    user = models.ForeignKey(User, related_name="secrets")
    secret = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = SecretManager()


class Like(models.Model):
    users = models.ForeignKey(User, related_name="userlikes")
    secret = models.ForeignKey(Secret, related_name="secretlikes")
    created_at = models.DateTimeField(auto_now_add=True)

apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from models import User
import bcrypt
from django.core.urlresolvers import reverse


def index(request):
    if 'id' in request.session:
        return redirect(reverse('secrets:index'))
    return render(request, 'login/index.html')


def process(request):
    verify = User.objects.regcheck(request.POST)
    if not verify[0]:
        pw = request.POST['pword1'].encode()
        user = User.objects.create(first_name=request.POST['first_name'],
                            last_name=request.POST['last_name'],
                            email=request.POST['email'],
                            pw_hash=bcrypt.hashpw(pw, bcrypt.gensalt()))

        userdict = {
            'id': user.id,
            'name': user.first_name.capitalize() + " " + user.last_name.capitalize()
        }
        request.session['id'] = userdict
        return redirect(reverse('secrets:index'))
    else:
        for i in range(len(verify[1])):
            messages.error(request, verify[1][i])
        return redirect(reverse('login:index'))


def login(request):
    return render(request, 'login/login.html')


def login_attempt(request):
    usercheck = User.objects.filter(email=request.POST['email'])
    if len(usercheck) < 1:
        messages.error(request, 'Invalid e-mail!')
        return redirect(reverse('login:login'))
    else:
        if User.objects.logcheck(usercheck[0].pw_hash, request.POST['pword']):
            userdict = {
                'id': usercheck[0].id,
                'name': usercheck[0].first_name.capitalize() + " " + usercheck[0].last_name.capitalize()
            }
            request.session['id'] = userdict
            return redirect(reverse('secrets:index'))
        else:
            messages.error(request, "Invalid password!")
            return redirect(reverse('login:login'))


def logout(request):
    request.session.clear()
    return redirect(reverse('login:login'))

apps/secrets/views.py
from django.shortcuts import render, redirect
from models import User, Secret, Like
from django.core.urlresolvers import reverse


def index(request):
    secretsBool = True
    secrets = Secret.objects.secretlist(request.session['id']['id'])
    if len(secrets) == 0:
        secretsBool = False
    context = {
        'secrets': secrets,
        'anysecrets': secretsBool,
        'user': User.objects.get(id=request.session['id']['id']).userlikes
    }
    return render(request, 'secrets/index.html', context)


def most_popular(request):
    # secrets = Secret.objects.all().order_by('-created_at')[:20]
    secrets = Secret.objects.most_popular(request.session['id']['id'])
    secretsBool = True
    if len(secrets) == 0:
        secretsBool = False
    context = {
        'secrets': secrets,
        'anysecrets': secretsBool
    }
    return render(request, 'secrets/mostpopular.html', context)


def create(request):
    Secret.objects.create(secret=request.POST['secret'],
                          user=User.objects.get(id=request.session['id']['id'])
                          )
    return redirect(reverse('secrets:index'))


def create_like(request, id):
    new_like, created = Like.objects.get_or_create(
        users=User.objects.get(id=request.session['id']['id']),
        secret=Secret.objects.get(id=id)
    )
    return redirect(reverse('secrets:index'))

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Register!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container">
        <div class="row">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <div class="col-md-2 col-md-offset-5">
                <h1 class="text-center">Register</h1>
                <form action="/process" method="POST" class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" name="first_name" class="form-control" id="first_name" placeholder="enter first name">
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" name="last_name" class="form-control" id="last_name" placeholder="enter last name">
                    </div>
                    <div class="form-group">
                        <label for="email">E-Mail</label>
                        <input type="text" name="email" class="form-control" id="email" placeholder="enter email">
                    </div>
                    <div class="form-group">
                        <label for="pword1">Password</label>
                        <input type="password" name="pword1" class="form-control" id="pword1" placeholder="enter password">
                    </div>
                    <div class="form-group">
                        <label for="pword2">Confirm Password</label>
                        <input type="password" name="pword2" class="form-control" id="pword2" placeholder="re-enter password">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Register</button>
                </form>
                <br>
                <form action="/login">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-block">Login</button>
                </form>
            </div>
        </div>
    </div>

</body>

</html>

apps/login/templates/login/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc=" crossorigin="anonymous"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-md-offset-5">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                    {% endif %}
                    <h1 class="text-center">Login</h1>
                    <form action="/login_attempt" method="POST" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email">E-Mail</label>
                            <input type="text" name="email" class="form-control" id="email" placeholder="enter email">
                        </div>
                        <div class="form-group">
                            <label for="pword">Password</label>
                            <input type="password" name="pword" class="form-control" id="pword" placeholder="enter password">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                    <form action="/">
                        {% csrf_token %}
                        <div class="form-group">
                        </div>
                        <button type="submit" class="btn btn-default btn-block">Register</button>
                    </form>
                </div>
            </div>
        </div>

    </body>
</html>

apps/secrets/templates/secrets/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Dojo `s~E~c~R~e~T~s'</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <style>
        body {
            background-image: url('https://media.giphy.com/media/4m4Z29t0Lq0Sc/giphy.gif');
            background-repeat: no-repeat;
            background-size: cover;
            color: #e1f4dc;
            text-shadow: 1px 1px 2px #0c2107;
        }

        .navbar {
            margin: 0 auto;
        }

        #gif {
            width: 100%;
            height: 100%;
            top: 0px;
            z-index:auto;
        }

        #secret {
            background-color: rgba(11, 22, 46, 0.7);
            padding: 10px;
        }

        .col-md-4 {
            height: 585px;
            overflow: scroll;
        }
    </style>
</head>

<body>
    <!-- begin navbar -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'secrets:index' %}"><span class="glyphicon glyphicon-home"></span></a>
            <p class="navbar-text">Signed in as {{ request.session.id.name}}</p>
            <form action="{% url 'login:logout' %}" class="navbar-form navbar-right">
                {% csrf_token %}
                <button type="submit" class="btn btn-default">Log Out</button>
            </form>
        </div>
    </nav>
    <!-- end navbar -->
    <div class="container-fluid" id="gif">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <form action="{% url 'secrets:create' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    <h1>Hello {{ request.session.id.name }}!</h1>
                    <div class="form-group">
                        <textarea name="secret" class="form-control" rows="4" placeholder="enter your secret......"></textarea>
                    </div>
                    <button type="submit" class="btn btn-default btn-lg">Tell Your Secret</button>
                </form>
                <a href="{% url 'secrets:most_popular' %}"><h2>Most Popular Secrets</h2></a>
            </div>
            <div class="col-md-4 col-md-offset-1">
                <h1 class="text-center">S E C R E T S</h1>
                {% if not anysecrets %}
                <h3 class="text-center">no secrets here...</h3>
                {% endif %}
                {% for secret in secrets %}
                <div id="secret">
                    <form action="{% url 'secrets:create_like' id=secret.0.id %}" method="post">
                        {% csrf_token %}
                        <p class="lead">
                            {{ secret.0.secret }}
                        </p>
                        <p>
                            ({{ secret.0.created_at | timesince }} ago)
                            <em> - {{ secret.0.secretlikes.count }} likes  </em>
                            {% if secret.1 %}
                            <em> - You've liked this!</em>
                            {% else %}
                        <button type="submit" class="btn btn-primary btn-xs" aria-label="Left Align">
                            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                        </button>
                        {% endif %}
                    </p>
                </form>
                </div>
                <br>
                {% endfor %}
            </div>
        </div>
</body>

</html>

apps/secrets/templates/secrets/mostpopular.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Dojo `s~E~c~R~e~T~s'</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <style>
        body {
            background-image: url('https://media.giphy.com/media/yow6i0Zmp7G24/giphy.gif');
            background-repeat: no-repeat;
            background-size: cover;
            color: #e1f4dc;
            text-shadow: 1px 1px 2px #0c2107;
        }

        .navbar {
            margin: 0 auto;
        }

        #gif {
            width: 100%;
            height: 100%;
            /*background-attachment: fixed;*/
            top: 0px;
            z-index:auto;
        }

        #secret {
            background-color: rgba(11, 22, 46, 0.7);
            padding: 10px;
        }

        .col-md-4 {
            height: 585px;
            overflow: scroll;
        }
    </style>
</head>

<body>
    <!-- begin navbar -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'secrets:index' %}"><span class="glyphicon glyphicon-home"></span></a>
            <p class="navbar-text">Signed in as {{ request.session.id.name}}</p>
            <form action="{% url 'login:logout' %}" class="navbar-form navbar-right">
                {% csrf_token %}
                <button type="submit" class="btn btn-default">Log Out</button>
            </form>
        </div>
    </nav>
    <!-- end navbar -->
    <div class="container-fluid" id="gif">
        <div class="row">
            <div class="col-md-5">
                <h1>Most Popular Secrets!</h1>
                <br>
                <br>
                <br>
                    <a href="{% url 'secrets:index' %}"><h2>Go Back To The Main Page</h2></a>
                </form>
            </div>
            <div class="col-md-4 col-md-offset-2">
                <h1 class="text-center">S E C R E T S</h1>
                {% if not anysecrets %}
                <h3 class="text-center">no secrets here...</h3>
                {% endif %}
                {% for secret in secrets %}
                <div id="secret">
                    <form action="{% url 'secrets:create_like' id=secret.0.id %}" method="post">
                        {% csrf_token %}
                        <p class="lead">
                            {{ secret.0.secret }}
                        </p>
                        <p>
                            ({{ secret.0.created_at | timesince }} ago)
                            <em> - {{ secret.0.secretlikes.count }} likes  </em>
                            {% if secret.1 %}
                            <em> - You've liked this!</em>
                            {% else %}
                        <button type="submit" class="btn btn-primary btn-xs" aria-label="Left Align">
                            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                        </button>
                        {% endif %}
                    </p>
                </form>
                </div>
                <br>
                {% endfor %}
            </div>
        </div>
</body>

</html>